version: 2
jobs:
  build:
    docker:
      - image: 137296740171.dkr.ecr.us-west-2.amazonaws.com/kairos-docker-build:production
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    working_directory: /opt/kairos/build-home/repo
    steps:
      - checkout
      - run: kairos_container_init
      - run:
          name: munge version
          command: |
            sed -i "s/0.3.2/0.3.2+kairos.${CIRCLE_BUILD_NUM}/" pgbedrock/__init.py__
      - run: kairos_python_package
      - run:
          name: publish package
          command: |
            PYPIRC=/opt/kairos/etc/pypirc
            TWINE="${KAIROS_DEPLOY_VENV:-/opt/kairos/util/deploy_venv}/bin/twine"

            if [[ "${CIRCLE_BRANCH}" =~ ^(kairos-release)$ ]]; then
              $TWINE upload -u $KAIROS_PUBLISH_USER -p $KAIROS_PUBLISH_API_KEY -r artifactory-python3 --config-file $PYPIRC ./dist/*
            else
              echo "No deployment configured for branch ${CIRCLE_BRANCH}"
            fi

notify:
  webhooks:
    - url: https://bdoa77w3h0.execute-api.us-west-2.amazonaws.com/webhook/
workflows:
  version: 2
  kairos-workflow:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - kairos-release
